---
- name: Generete oc-mirror imagesetconfigs for {{ item }}
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ common_openshift_oc_mirror_dir }}/{{ item }}"
  register: template_result

- name: Run oc-mirror to generate {{ item }} tar
  ansible.builtin.command: 
    cmd: "{{ common_openshift_client_bin }}/oc-mirror --config {{ common_openshift_oc_mirror_dir }}/{{ item }} \
      file://{{ common_openshift_oc_mirror_dir }}/{{ item.split ('.')[0] }} {{ '--v2' if common_oc_mirror_v2 | default(false) | bool else '' }}"
  environment:
    OC_MIRROR_CACHE: "{{ common_openshift_oc_mirror_dir }}/.cache"
    OCP_SIGNATURE_VERIFICATION_PK: "{{ common_openshift_oc_mirror_dir }}/pgpkey"
  register: mirror_pull
  when: template_result.changed | bool
  retries: 5
  delay: 10
  failed_when: mirror_pull.stdout is search("error|failed|timeout|permission denied|mirror failed|unable to fetch|invalid signature", ignorecase=True)
  until: mirror_pull.rc == 0

- name: Remove pull download dirs
  ansible.builtin.file:
    path: "{{ download_dirs }}"
    state: absent
  loop:
    - "{{ common_openshift_oc_mirror_dir }}/{{ item.split ('.')[0] }}/oc-mirror-workspace"
    - "{{ common_openshift_oc_mirror_dir }}/.cache"
  loop_control:
    loop_var: download_dirs
  when: template_result.changed | bool
