---
- name: Set fact for {{ common_ip_space }} IPv4 address
  set_fact:
    ipv4_address: "{{ ansible_all_ipv4_addresses | select('match', '^' + common_ip_space + '\\.') | list }}"
  when: ipv4_address is undefined

- name: Debug image path for iso file
  ansible.builtin.debug:
    msg: "image path: {{ ipv4_address | first }}:{{ media_share_webserver_port }}/agent.x86_64.iso"
  when: debug is defined and debug | bool

- name: Insert image file using HTTP.
  delegate_to: localhost
  dellemc.openmanage.idrac_virtual_media:
    idrac_ip: "{{ media_share_idracs.ip }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    validate_certs: false
    force: true
    virtual_media:
      - insert: true
        image: "http://{{ ipv4_address | first }}:{{ media_share_webserver_port }}/agent.x86_64.iso"
        media_type: "CD"

- name: Boot Once via CD
  delegate_to: localhost
  dellemc.openmanage.idrac_boot:
    idrac_ip: "{{ media_share_idracs.ip }}"
    idrac_user: "{{ idrac_user }}"
    idrac_password: "{{ idrac_password }}"
    validate_certs: false
    boot_source_override_target: cd
    boot_source_override_enabled: once
    reset_type: force_restart